### ISSUE TITLE
uflo JumpNode类添加显示名称

### ISSUE THREAD

**Issue by sunshanjin** [youseries/uflo#10]
1、使用uflo流程引擎时，使用taskService.getAvaliableRollbackTaskNodes(taskId);能够获取可退回的节点，但是获取的节点并没有包含节点名称对应的显示名称；
2、下个版本能否将显示名称也添加上；
3、涉及到的类：com.bstek.uflo.command.impl.jump.JumpNode；
谢谢！
![qq 20171016170025](https://user-images.githubusercontent.com/7366954/31603707-899d208e-b293-11e7-9c7b-50a54a7e225e.png)

**Comment by youseries** [comment]
最新版本SNAPSHOT已添加此功能，请测试，谢谢。
