### ISSUE TITLE
路由决策条件表达式异常

### ISSUE THREAD

**Issue by ltxiang** [youseries/uflo#12]
1、编写了表达式后点击其它任务节点，再点击路由决策节点属性面板的条件表达式呈现异常。
2、打开写了条件表达式的路由决策模板报错，异常信息：
Error on line 1 of document  : 元素类型 "decision" 必须后跟属性规范 ">" 或 "/>"。 Nested exception: 元素类型 "decision" 必须后跟属性规范 ">" 或 "/>"。

**Comment by youseries** [comment]
最新版中已修复
