### ISSUE TITLE
关于UFLO2流程设计模板添加动态分支节点之后无法发布使用

### ISSUE THREAD

**Issue by yandixuan** [youseries/uflo#16]
## 这是设计图demo
![qq 20171123153606](https://user-images.githubusercontent.com/23276822/33162675-bf7dd410-d065-11e7-98e2-a9a1a27808d9.png)

## 这是console 报错
![fr bw 5 3g y ywa2eu bg](https://user-images.githubusercontent.com/23276822/33163162-0ae14872-d068-11e7-991f-046f7ad94a58.png)

**Comment by youseries** [comment]
已修复，请更新最新的SNAPSHOT测试，谢谢！
