### ISSUE TITLE
2.0.6快照版hibernate生成表结构时bug

### ISSUE THREAD

**Issue by quqiangsheng** [youseries/uflo#17]
2.0.6快照版
hibernate5.2.x
生成表oralce 11g结构时
多出来了以下表感觉不太正常 mysql下不会生成这些 但oralce下多了这些 感觉应该是bug
![uflo](https://user-images.githubusercontent.com/9816930/33182895-a9932254-d0b0-11e7-8fd4-9cdbf3d6cd72.jpg)
红框的四个表

**Comment by youseries** [comment]
不知道，这些表不是UFLO的，UFLO也不会创建这些表，检查下你项目是不是自己加了这些表！

**Comment by quqiangsheng** [comment]
我也没有建 好吧 我在找找原因
