### ISSUE TITLE
查看已部署的流程图时，节点名字过长会显示不全

### ISSUE THREAD

**Issue by qq313687396** [youseries/uflo#19]
![inked721acb860fb69bad7ef55aac65aeac09_li](https://user-images.githubusercontent.com/20849915/33297459-0fb7ea4c-d41c-11e7-89ed-d51d9bb2e058.jpg)
![inked0bd2f5fb86e89fb9c027844c32eb5c4a_li](https://user-images.githubusercontent.com/20849915/33297472-24420006-d41c-11e7-8090-c8d4c1f2d40e.jpg)

貌似在边缘的节点会显示不全，试过把连接线缩短，节点整体向左边移动，还是显示不全。

**Comment by youseries** [comment]
已修复，请更新最新的SNAPSHOT测试，谢谢。
