### ISSUE TITLE
组件访问控制API是什么

### ISSUE THREAD

**Issue by weiqunjiang** [youseries/uflo#2]
人工节点属性标签配置的控件权限对应的Java API是什么？

**Comment by youseries** [comment]
什么组件？

**Comment by youseries** [comment]
通过TaskNode对象的getComponentAuthority方法获取当前任务节点上配置的组件权限信息。如何获取TaskNode可通过下面的方法实现：
1.根据taskId取到对应的Task对象
2.从Task对象中取到对应的processId
3.利用ProcessService根据processId取到对应的ProcessDefinition对象
4.从ProcessDefinition对象中取到Task对象对应的TaskNode对象
5.从TaskNode对象用getComponentAuthority方法获取当前任务节点上配置的组件权限信息
6.根据取到的组件权限控制信息，设置页面组件权限
