### ISSUE TITLE
关于UFLO 待办任务页面 处理完任务后数据没刷新

### ISSUE THREAD

**Issue by yandixuan** [youseries/uflo#20]
### 处理完任务后数据没刷新。

**Comment by youseries** [comment]
最新版的SNAPSHOT中已添加可以刷新待办任务列表、待领取任务列表以及历史任务列表方法，具体见：
http://wiki.bsdn.org/pages/viewpage.action?pageId=30441805
- 处理任务的业务页面在完成任务后关闭弹出窗口的方法
执行JS：window.parent.dialogEvent.eventEmitter.emit(window.parent.dialogEvent.CLOSE_DIALOG)
- 在自定义处理任务页面里刷新待办任务列表方法
执行JS：window.parent.todoEvent.eventEmitter.emit(window.parent.todoEvent.RELOAD_TODO);
- 在自定义处理任务页面里刷新待领取任务列表方法
执行JS：window.parent.todoEvent.eventEmitter.emit(window.parent.todoEvent.RELOAD_CLIAM);
- 在自定义任务处理页面里刷新历史任务列表方法
执行JS：window.parent.todoEvent.eventEmitter.emit(window.parent.todoEvent.RELOAD_HISTORY);
