### ISSUE TITLE
会签过程的一票否决如何实现？

### ISSUE THREAD

**Issue by hdffpff** [youseries/uflo#24]
现有流程需求在会签时，要求全部会签人员全部审批通过时，向下流转，如果会签人员中有一个审批人审批未通过，则其他审批人不需要再审，直接结束流程。请问这类需求如何实现？

**Comment by youseries** [comment]
会签类型任务，可以通过设置“完全指定任务数”来实现你这里的“一票否决”功能，如设置为1，这样就表示只有会签任务中有一个完全流程即离开当前任务节点，具体见：
http://wiki.bsdn.org/pages/viewpage.action?pageId=32079884
