### ISSUE TITLE
关于uflo中用户筛选的时候所使用的功能，我有点个人建议，多多包涵

### ISSUE THREAD

**Issue by 294033186** [youseries/uflo#25]
我觉得对于AssigneeProvider这个接口的实现类她所走的流程是先去调queryEntities(PageQuery<Entity> pageQuery, String parentId)这个方法获取筛选用户的条件然后流程对应的任务启动后在调用getUsers(String entityId, Context context, ProcessInstance processInstance)这个方法根据entityId去查询对应的用户来返回任务处理人。所以前端页面上的部分ui应该需要优化一下
![ij7o xakj 6 ymw h xt3](https://user-images.githubusercontent.com/31615469/34374878-66ea79ce-eb1e-11e7-925a-17917ecb495d.png)

**Comment by 294033186** [comment]
我这中理解可能有点另类，不过如果我在页面上需要指定角色然后后台再根据角色去查询用户信息的话，这个ui的叫法就有点牵强了。

**Comment by youseries** [comment]
这里的“参与者”叫法实际上是对任务处理人的统称，选的人，这个人是参与者，选角色，角色就是参与者，我理解下来没啥不妥，如果有不同想法请说明 ，谢谢。

**Comment by 294033186** [comment]
明白了，谢谢
