### ISSUE TITLE
关于任务节点的用户自定义数据的功能修改无法保存，请关注谢谢。

### ISSUE THREAD

**Issue by 294033186** [youseries/uflo#26]
![image](https://user-images.githubusercontent.com/31615469/34378460-d9667522-eb30-11e7-83c7-844b2ad4800e.png)

**Comment by youseries** [comment]
你用的uflo什么版本？这个bug我记得在2.1.0 release时就处理过，你可以更新试试，谢谢。

**Comment by 294033186** [comment]
2.1.0存在一个条件bean无法保存的问题，你们说2.1.1-snapshot修复了我就升级了，结果自定义数据无法修改。

**Comment by youseries** [comment]
BUG，最新的2.1.1-snapshot已修复，请更新测试，谢谢。

**Comment by 294033186** [comment]
ok
