### ISSUE TITLE
希望添加hibernate5.x的支持

### ISSUE THREAD

**Issue by quqiangsheng** [youseries/uflo#3]
全新的流程引擎为了以后的长远发展建议支持下hibernate5.x 变化不算多 难度应该不大 新的项目选型流程引擎也希望相关依赖保持新一些 长远来看有好处

**Comment by youseries** [comment]
会支持的。

**Comment by youseries** [comment]
刚release的2.0.0正式版中就包含hibernate5版本，谢谢。
