### ISSUE TITLE
uflo回退

### ISSUE THREAD

**Issue by yuxuanxinchen** [youseries/uflo#30]
请问uflo能够填补activiti的回退功能不

**Comment by youseries** [comment]
看TaskService，里面有回退任务的API。

**Comment by 294033186** [comment]
您好高大师，看了我们uflo的撤回功能，发现有点不满足我们的需求，可能是因为我们的需求比较特殊吧，需求就是我们撤回的时候需要支持一级一级的撤回，而调用现有的撤回方法可能会出现在两个节点间出现死循环的撤回，就是a->b->c->d,走到d的时候c要发起撤回那么撤回到了c，b也要撤回那么b发起撤回发现撤回到了d......
