### ISSUE TITLE
uflo流程结束判断

### ISSUE THREAD

**Issue by yuxuanxinchen** [youseries/uflo#33]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UFlo的具体版本号：
最新版

*  #### 遇到的问题详细描述：
流程结束的时候，在流程的时候如何判断，断点看在结束流程的前一个节点通过流程service去查询流程实例获取到的对象是空的，能否通过这个判断呢，

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
最简单的方法就是通过ProcessService取某个流程实例ID对应的流程实例对象，如果返回null说明已结束。
当然一般可以在流程的结束节点加个Event类，比如可以在这个类里向某个业务表某个字段写入一个值，表明流程流转到结束节点流程结束。
