### ISSUE TITLE
关于登录用户和处理人的名字显示问题

### ISSUE THREAD

**Issue by squallliu** [youseries/uflo#35]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UFlo的具体版本号：

2.1.1

*  #### 遇到的问题详细描述：

在uflo中所有关于人名字都是显示的username，但实际业务中是要显示登录账号对应的真实人名的，uflo有什么方法能做到吗？

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
你可以利用uflo提供的api自己做符合业务要求的页面，比如待办任务列表，监控中心等页面。
