### ISSUE TITLE
如何通过给流程节点添加事件，获取下一节点处理人（通过/驳回）

### ISSUE THREAD

**Issue by Janch-Zhaodw** [youseries/uflo#36]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UFlo的具体版本号：
uflo-console-2.1.1

*  #### 遇到的问题详细描述：
如何通过给流程节点添加事件，获取下一节点处理人（通过/驳回）

*  #### 涉及到的异常信息（完整异常信息）：无

*  #### 相关截图：无

**Comment by youseries** [comment]
取不到。
