### ISSUE TITLE
nginx代理springboot内置的tomacat后静态js,css都加载不了，请问nginx怎么配置才能访问

### ISSUE THREAD

**Issue by favesing** [youseries/uflo#39]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UFlo的具体版本号：
2.1.1

*  #### 遇到的问题详细描述：
  1 server {
  2     listen       80;
  3     server_name  loalhost;
  4
  5     index index.html index.htm
  6
  7     charset utf-8;
 15
 16     location / {
 17         proxy_set_header X-Real-IP $remote_addr;
 18         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 19         proxy_set_header Host $http_host;
 20         proxy_pass http://localhost:8080;
 21     }
          location ~* \.(gif|jpg|jpeg|bmp|png|ico|txt|js|cs|js)$ {
 32         expires 30d;
 33     }

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
不知道。
