### ISSUE TITLE
设计器选择参与者时分页显示bug

### ISSUE THREAD

**Issue by quqiangsheng** [youseries/uflo#4]
左下角那个第几页翻页的空白不显示
![image](https://user-images.githubusercontent.com/9816930/29567968-6f7e1772-8781-11e7-8422-6672dd212070.png)
`	/**
	 * 分页方式查询返回具体的任务处理人，可以是具体的人，也可以是部门等之类容器型对象
	 * @param pageQuery 用于包装分页信息的查询对象
	 * @param parentId 上级实体对象的ID，可能为空
	 */
	public void queryEntities(PageQuery<Entity> pageQuery, String parentId) {		
		int index=pageQuery.getPageIndex();
		int size=pageQuery.getPageSize();
		Example example =new Example(SysUser.class);
		List<SysUser> findList=sysUserService.selectByExampleAndRowBounds
				(example, new RowBounds((index-1)*size, size));
		pageQuery.setRecordCount(sysUserService.selectCountByExample(example));
		
		List<Entity> entitys=new ArrayList<Entity>();
		for (SysUser sysUser : findList) {
			entitys.add(new Entity(sysUser.getUserId(),sysUser.getUserName()));
		}
		pageQuery.setResult(entitys);
	}`
参照你之前的例子读取我系统的用户表有1500多条 
uflo.disabledUserAssigneeProvider=true设置为true后 
预设的测试数据   “指定用户”  那一个关不掉

 我的版本console和core都是2.0.0正式版hibernate5版

建议项目在oschina上做个镜像同步github
 github在中国访问有时候太抽风了

**Comment by quqiangsheng** [comment]
分页在eclipse插件中显示正常 可能是前台js问题

propertyConfigurer中order调低 才能覆盖jar包中的默认配置

**Comment by youseries** [comment]
分页的BUG已修复，uflo.disabledUserAssigneeProvider=true属性不能覆盖的问题我本地未能重现，请检查你的properties文件的加载方式，我采用的是uflo中提供的加载属性文件方式：
`	<bean id="propertyConfigurer" parent="uflo.props">
		<property name="location">
			<value>/WEB-INF/config.properties</value>
		</property>
	</bean>`

**Comment by quqiangsheng** [comment]
好的
