### ISSUE TITLE
当前任务为竞争类型，待处理任务获取相同的两条数据

### ISSUE THREAD

**Issue by Janch-Zhaodw** [youseries/uflo#40]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UFlo的具体版本号：
uflo-console-2.1.2
*  #### 遇到的问题详细描述：
当前任务为竞争类型，待处理任务获取相同的两条数据
*  #### 涉及到的异常信息（完整异常信息）：
*  #### 相关截图：
<img width="945" alt="qq20180126-162212 2x" src="https://user-images.githubusercontent.com/32115566/35430878-180fb0ae-02b5-11e8-92b4-85e453b337c1.png">
<img width="661" alt="qq20180126-162305 2x" src="https://user-images.githubusercontent.com/32115566/35430902-3af7aa18-02b5-11e8-88e4-66a1079f20c3.png">

**Comment by youseries** [comment]
这种问题应该出在你的UI上，你可以在后台代码List<Task> tasks=query.list()处加上断点，看看取到的tasks是哪些，以确定问题的原因。

**Comment by Janch-Zhaodw** [comment]
断点跟到List tasks=query.list()这个地方获取的也是两条

**Comment by Janch-Zhaodw** [comment]
<img width="1069" alt="qq20180201-163939 2x" src="https://user-images.githubusercontent.com/32115566/35668975-89d31b64-076e-11e8-8b54-e3a189960f5b.png">
