### ISSUE TITLE
有关任意节点发起会签的问题

### ISSUE THREAD

**Issue by luoxiaop** [youseries/uflo#41]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UFlo的具体版本号：2.0.2

*  #### 遇到的问题详细描述：目前在项目中需要在任意节点发起会签审批，请问可以如何实现，多谢支持。

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
那就将任务节点类型设置为会签节点，然后通过TaskService动态加减签即可
