### ISSUE TITLE
IE11下面，流程设计功能（design)有问题

### ISSUE THREAD

**Issue by jktantan** [youseries/uflo#42]
*  #### 当前使用的UFlo的具体版本号：2.1.2 
*  #### 遇到的问题详细描述：
在IE11下面，流程图design的功能有如下问题：
1. 部分操作图标因为在CSS中没有增加format('embedded-opentype')，导致权限不足，从而无法显示。
2. 因为IE11不支持es6的API,且没有使用polyfill.min.js，导致功能无法使用。

**Comment by youseries** [comment]
不支持IE
