### ISSUE TITLE
uflo-hibernate4-2.1.2版本流程模板保存后不能重新打开

### ISSUE THREAD

**Issue by wisedu-wlwang** [youseries/uflo#43]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UFlo的具体版本号：
    uflo-hibernate4-2.1.2

*  #### 遇到的问题详细描述：
    在2.1.2版本上面新建的流程，重新打开的时候报错，流程文件中出现undefined，怀疑保存流程文件有问题

*  #### 涉及到的异常信息（完整异常信息）：
![image](https://user-images.githubusercontent.com/34290800/36848936-ad529fd4-1d9d-11e8-8a16-95fa758fd403.png)

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/34290800/36848972-ca00b54e-1d9d-11e8-9fe1-7c799c0b1ffb.png)
![image](https://user-images.githubusercontent.com/34290800/36849024-e32351d0-1d9d-11e8-87bd-931bb75acda1.png)
![image](https://user-images.githubusercontent.com/34290800/36849052-fa31002a-1d9d-11e8-86dc-a94270737ce0.png)

**Comment by wisedu-wlwang** [comment]
在uflo-2.12上测试没问题，感觉像是uflo-hibernate4-2.1.2的jar包有问题

**Comment by youseries** [comment]
看了下代码，应该是你启用了任务的“过期动作”，但却没有配置具体时间导致，最新的SNAPSOHT中加了保护，你可以重现做个模版试试。
