### ISSUE TITLE
 流程中心领取任务请求报错

### ISSUE THREAD

**Issue by wisedu-wlwang** [youseries/uflo#44]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UFlo的具体版本号：
    uflo-2.1.2

*  #### 遇到的问题详细描述：
    流程中心领取任务请求报错，应该是js请求名称和后端名称不一致导致，js中请求名称是loadCliamUsers，后端名称为loadClaimUsers

*  #### 涉及到的异常信息（完整异常信息）：
![image](https://user-images.githubusercontent.com/34290800/36850660-53a5542c-1da2-11e8-8dbd-7fa5aa4f0940.png)

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/34290800/36850678-60968930-1da2-11e8-9d81-a8e2c1e42076.png)

**Comment by youseries** [comment]
BUG ,最新的SNAPSHOT中已修复，谢谢。
