### ISSUE TITLE
2.1.2 版本 在启动项目时，流程处理人是‘user2’。为什么非此用户也能处理此流程。

### ISSUE THREAD

**Issue by lijin93** [youseries/uflo#47]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UFlo的具体版本号：2.1.2

*  #### 遇到的问题详细描述：
在画流程图时，有一节点设置的处理人是“user2”,但是在部署后，处理此节点时，非“user2”用户，也可处理此节点，之后此节点的一些信息查看时便报错了。

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
你应该通过todo页面去处理任务，而不应该通过监控测试中心。
如果不懂流程思想的话，还是先去学习下吧。
