### ISSUE TITLE
带分支节点的流程图，未经过聚合结束流程之后，UFLO_HIS_TASK清空

### ISSUE THREAD

**Issue by stevenTianbin** [youseries/uflo#48]
JAR包版本：UFLO-CORE 2.0.0;BDF2-UFLO 2.1.2;

问题描述：流程图中有分支节点，在聚合节点之前结束流程，业务表单页面的审批意见为空。
或者分支之后因业务需要，没有聚合节点，而是两个分支分别配置了结束节点，但流程结束后业务表单页面的审批意见也为空。

因无法上传图片我用文字来描述一下我碰到的问题：
在上面我说明了流程未流经分支聚合对的情况下结束流程，会导致UFLO_HIS_TASK表相关记录被清空。在看过您写的源码我发现，您在处理分支节点时是将分支与主路径信息保存在UFLO_PROCESS_INSTANCE中，比如分支有两条，则在UFLO_PROCESS_INSTANCE会出现3条记录。如果分支流过聚合节点后，程序会将分支在UFLO_PROCESS_INSTANCE表中记录删除。一般流程都会以分支聚合对出现，但是有些特殊情况，比如：1、在聚合节点之前满足特定条件，流程进入结束节点。2、分支之后，分支不需要再聚合，有自己的分支结束节点。在这些情况下，ENDNODE类的completeProcessInstance方法106-111行是这样处理的，对于这个流程所有UFLO_PROCESS_INSTANCE的记录，如果id等于根流程实例id不作处理，如果不等于则调用ProcessService的deleteProcessInstance方法，在该方法中您会删除HistoryTask、HistoryActivity等实体类的数据。如果业务表单的审批意见，是使用这些表的数据的话，会使这些信息为空。
这些代码在您的UFLO-CORE 包中，请您能尽快解决这些问题。

**Comment by youseries** [comment]
已做改进，更新最新的SNAPSHOT试试，谢谢。

**Comment by stevenTianbin** [comment]
谢谢，这个问题已经解决。
