### ISSUE TITLE
分支结束后，非处理人打开流程追踪报错，流程图无法显示。

### ISSUE THREAD

**Issue by stevenTianbin** [youseries/uflo#49]
问题jar包：uflo-console 1.1.5

在使用分支聚合对常会碰到一个问题，就是流程图中有分支时，当其中的第一个分支结束后，如果非当前处理人打开流程追踪会弹出Error:error的提示框，而流程图无法显示。

根据后台报错，在uflo-console 1.1.5 下dorado/scripts/uflo-process-router-diagram.js中的this.show方法，使用了ajax调用了/cimsp/dorado/uflo/show.process.diagram这个bean(是这个叫法？),也就是ProcessDiagramController类。在该类的第266行报了一个NullPointException的错误,导致弹出Error:error的提示框。

该问题比较紧急，请加急解决，谢谢。

**Comment by youseries** [comment]
我这里没问题，如下图所示：
![demo](https://user-images.githubusercontent.com/29193502/38181642-98babe6c-3666-11e8-9e07-4cd4e936491f.png)
应该是你们版本太老导致，请升级到最新版或对照最新版com.bstek.uflo.console.handler.impl.diagram.ProcessDiagramServletHandler类源码，替换ProcessDiagramController类
