### ISSUE TITLE
不知道有没有接口，来修改DAO部分

### ISSUE THREAD

**Issue by linziguan** [youseries/uflo#5]
因为有很多国内项目采用mybatis或beetlSQL(http://www.ibeetl.com/)。不知道有没有接口，来让修改DAO部分，以兼容不同的orm技术。

**Comment by youseries** [comment]
uflo依赖于hibernate，这是不能更改的，但你的业务部分可以使用其它的ORM，这点没有限制！

**Comment by wendal** [comment]
这算beetlSQL的软广告吗?? 那我也打一个广告 https://github.com/nutzam/nutz
