### ISSUE TITLE
支持分支状态下主节点的拿回功能

### ISSUE THREAD

**Issue by stevenTianbin** [youseries/uflo#50]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UFlo的具体版本号：
uflo-core2.0.0.jar

*  #### 遇到的问题详细描述：
当主节点提交到分支节点后，若分支的两条路径都经过的话，在主节点使用拿回功能时报错，但若分支仅经过一条路径时，主节点可以正常使用拿回功能。

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
不支持这种拿回
