### ISSUE TITLE
删除分支时，分支流程中的任务不能删除

### ISSUE THREAD

**Issue by yetao-study** [youseries/uflo#53]
*  #### 当前使用的UFlo的具体版本号：
2.1.2

*  #### 遇到的问题详细描述：
删除分支时，分支流程中的任务不能删除

*  #### 涉及到的异常信息（完整异常信息）：
删除分支时，分支流程中的任务不能删除

*  #### 相关截图：
uflo/uflo-core/src/main/java/com/bstek/uflo/command/impl/DeleteProcessInstanceCommand.java
这个文件中80行
processInstance.getId()
应为pi.getId()
否则出现删除分支，分支下实例的Task删不掉的情况

**Comment by youseries** [comment]
确实如LZ所说，目前在最新版的SNAPSHOT中已修复，请更新测试，谢谢。
