### ISSUE TITLE
人工任务过期提醒任务过多，项目启动太慢

### ISSUE THREAD

**Issue by Li1993** [youseries/uflo#54]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UFlo的具体版本号：
2.1.2

*  #### 遇到的问题详细描述：
因为基本每个任务都需要过期提醒，在项目启动过程中com.bstek.uflo.service.impl.SchedulerServiceImpl的addReminderJob方法中会一直获取任务信息。导致项目启动非常慢。目前放了2000多数据进行测试启动都需要5分钟左右，实际数据有几十万，而且以后数据会越来越多。请问这种情况有什么方法可以解决或者避免么

*  #### 涉及到的异常信息（完整异常信息）：
无异常

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/17410376/38316365-2124fc8e-385d-11e8-8436-67d3a2983fd0.png)
![image](https://user-images.githubusercontent.com/17410376/38316733-f22f8a1a-385d-11e8-901b-05f8c519a1ba.png)
![image](https://user-images.githubusercontent.com/17410376/38317347-71199e6e-385f-11e8-987a-105cf2dde343.png)

**Comment by youseries** [comment]
对于要提醒 的任务来说，启动的时候需要加载到内存，所以这个工作不可少，在实际应用当中，任务一旦被完成或删除，那么对应的提醒job也将被删除，所以job的多少取决于正在处理中的任务数量。
目前来说，没有其它办法可以避免这个工作，对于你这里来说可以考虑把hibernate日志关闭，这样可能会快一些。
