### ISSUE TITLE
请问UFLO支持多租户(动态数据源)吗

### ISSUE THREAD

**Issue by bigrats** [youseries/uflo#56]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UFlo的具体版本号：

*  #### 遇到的问题详细描述：
我们客户的要求开发部署一套流程系统, 内部各个子公司的数据库是独立的.
UFLO使用hibernate存储数据, 可以配置使用AbstractRoutingDataSource动态数据源实现, 不知道UFLO内部是否支持允许过程中的数据源切换. 

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
这个需要你自己解决，帮不了你。
