### ISSUE TITLE
分支节点需要做什么处理吗？完成分支任务之后，无法聚合

### ISSUE THREAD

**Issue by liudashi2006** [youseries/uflo#57]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UFlo的具体版本号：2.1.2

*  #### 遇到的问题详细描述：如下图所示，一张最简单的流程图，分支下连线未做任何处理，直接连到人工任务，在人工任务1完成后，可流转到下方三个分支任务，但办理完成后，无法聚合，聚合节点也是默认状态。数据库中查看相关内容，在uflo_process_Instance表中，仍然显示currentNode为分支节点，current_task也是人工任务1，请问这个是为什么呢？我办理任务的时候缺少了什么动作吗？

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![1](https://user-images.githubusercontent.com/34768033/38867640-29bd57fa-4277-11e8-8484-6b676fa40953.png)
![2](https://user-images.githubusercontent.com/34768033/38867886-e06d6152-4277-11e8-8e8f-fc83c0f1b65b.png)
![3](https://user-images.githubusercontent.com/34768033/38867922-fae1fa2a-4277-11e8-8a5b-b458b921082d.png)
办理任务的方法
![4](https://user-images.githubusercontent.com/34768033/38867998-3286131c-4278-11e8-9e8b-a0bd2976b8b3.png)

**Comment by youseries** [comment]
从代码上看没发现问题，可以在监控中心试试看流程能不能正常流转。

**Comment by liudashi2006** [comment]
您好，我跟您具体描述一下，今天早晨做了个测试，打断点跟了一下，就是我分支任务办理到最后一个的时候，JoinNode在Enter方法中，有3个返回true的方法，由于我没有设置条件，会直接来到最后一个比较方法，`else if(noneCompleteProcessInstances.size()==0){
			return true;
		}` 这个代码块里，但办理最后一个分支任务的时候，是用noneCompleteProcesssInstance的长度判断的，那么问题就来了，办理最后一个任务的时候，走到这个判断条件的时候，是必然会取到长度为1的实例的，所以这个永远不会等于0，所以永远不会返回true，可能是我少做了什么处理吗？但是任务列表中两个都是已完成状态，不应该在个人待办列表中出现，所以也无法再继续往下办理，而聚合节点又不会生成任务，所以我这里不知道该怎么处理，让任务继续推进了

**Comment by liudashi2006** [comment]
搞定，是因为jpa事务和hibernate事务管理分歧导致的，分别配置两个事务就可以了

**Comment by liuyibing123456** [comment]
@liudashi2006 请问解决办法是否是hibernate事务管理uflo，jpa事务管理业务逻辑，我也遇到了session.delete的问题
