### ISSUE TITLE
SchedulerServiceImpl应该添加destroy-method

### ISSUE THREAD

**Issue by wendal** [youseries/uflo#6]
当前2.0.0版本的SchedulerServiceImpl持有org.quartz.Scheduler,但是程序关闭的时候没有关闭它,导致tomcat无法关闭. 建议添加destroy-method

**Comment by youseries** [comment]
最新版中已加上destroy-method，谢谢。

**Comment by wendal** [comment]
建议在提交的时候, comment用  fix #6  的github语法, 这样会自动关联和close issue

**Comment by youseries** [comment]
好的，谢谢。
