### ISSUE TITLE
2.1.3 访问todo路径出现js错误

### ISSUE THREAD

**Issue by louisliaoxh1989** [youseries/uflo#64]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UFlo的具体版本号：
UFlo的具体版本号:2.1.3 

*  #### 遇到的问题详细描述：

访问todo路径出现js错误后页面无法正常访问
*  #### 涉及到的异常信息（完整异常信息）：

访问todo路径出现js错误后页面无法正常访问: Cannot read property 'array' of undefined 
是报的todo.bundle.js
*  #### 相关截图：

**Comment by youseries** [comment]
更新到最新的2.1.4-SNAPSHOT即可。
