### ISSUE TITLE
请问能提供表结构的详细定义吗

### ISSUE THREAD

**Issue by mickeyz** [youseries/uflo#69]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UFlo的具体版本号：

*  #### 遇到的问题详细描述：
请问能提供表结构的详细定义吗

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
表结构由Hibernate自动生成，提供不了。
