### ISSUE TITLE
uflo处理任务节点,页面显示流程图时报错.

### ISSUE THREAD

**Issue by huangde2000** [youseries/uflo#7]
uflo处理任务节点,页面显示流程图时报错.错误为:

IndexSizeError: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-23.2) is negative.

具体可以参见截图.
![uflo](https://user-images.githubusercontent.com/2030840/29852599-9b444998-8d6d-11e7-8aff-7d3fe1631312.png)

**Comment by huangde2000** [comment]
这个问题出现了不知道如何排查.请予以指导,.

**Comment by youseries** [comment]
请提供完整异常堆栈，谢谢。

**Comment by huangde2000** [comment]
好像跟视图里面,流程图不能完整显示有关系.
现在调整了流程图的高度,并调整了显示控件的高度就没这个问题了.
