### ISSUE TITLE
2.1.2仓库里的包有问题

### ISSUE THREAD

**Issue by funyule** [youseries/uflo#70]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UFlo的具体版本号：
2.1.2

*  #### 遇到的问题详细描述：
竞争型任务领取异常

查看master的代码，发现这个问题已经解决。能否更新一版中央仓库中的包，谢谢

*  #### 涉及到的异常信息（完整异常信息）：
![image](https://user-images.githubusercontent.com/12372048/43674312-a046da62-9804-11e8-8f80-6b36c805394b.png)

*  #### 相关截图：
jsl里的方法名：
![image](https://user-images.githubusercontent.com/12372048/43674299-79622bf4-9804-11e8-98a0-b418f514a75a.png)
Java对应的方法名：
![image](https://user-images.githubusercontent.com/12372048/43674302-8256f186-9804-11e8-9588-bf05f8bf5d7a.png)

**Comment by funyule** [comment]
看到 #44 问题中已经修复该问题。但是2.1.2这个release包却不能使用....

**Comment by youseries** [comment]
试试最新版
