### ISSUE TITLE
子流程：完成子流程开始节点可能存在的任务的选项不能固定住

### ISSUE THREAD

**Issue by fanjungitlab** [youseries/uflo#71]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UFlo的具体版本号：
2.1.3版本

*  #### 遇到的问题详细描述：
子流程配置界面上：完成子流程开始节点可能存在的任务的选项，我选了是，保存，并发布，之后，在我次打开含有这个子流程的流程图，这个选择会变到否上。

*  #### 涉及到的异常信息（完整异常信息）：
无后台异常，请看截图

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/40688587/44023111-2dd2ad16-9f1c-11e8-934c-395fa7c01d57.png)

在次打开流程图
![image](https://user-images.githubusercontent.com/40688587/44023168-4a9f25b4-9f1c-11e8-9f79-abbf90a5ce68.png)

该问题会导致，你如果修改了流程图，但是没去把子流程里去点到是，那么就会默认把错误的否保存进去，这样影响很大，请尽快核实，谢谢

**Comment by youseries** [comment]
最新版中已修复。
