### ISSUE TITLE
某个任务节点结束流程

### ISSUE THREAD

**Issue by zykcome** [youseries/uflo#75]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UFlo的具体版本号：2.1.5

*  #### 遇到的问题详细描述：怎么样在某个任务节点，审批拒绝后，直接结束流程的

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by kilma01** [comment]
直接forward到结束节点

**Comment by zykcome** [comment]
> 直接forward到结束节点

在分支的时候，不行的呀
