### ISSUE TITLE
central 中领取任务错误

### ISSUE THREAD

**Issue by xiaooiax** [youseries/uflo#83]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UFlo的具体版本号：

2.1.4

*  #### 遇到的问题详细描述：
前端请求路径：
127.0.0.1/uflo/central/cliamTask
CentralServletHandler 类中的方法名
claimTask

*  #### 涉及到的异常信息（完整异常信息）：
java.lang.NoSuchMethodException: com.bstek.uflo.console.handler.impl.central.CentralServletHandler.cliamTask(javax.servlet.http.HttpServletRequest, javax.servlet.http.HttpServletResponse)

*  #### 相关截图：

**Comment by kilma01** [comment]
的确是，我测试也是，但是不影响用api领取任务

**Comment by youseries** [comment]
老版本的bug，可以试试最新版。
