### ISSUE TITLE
uflo历史流程与任务中结束日期显示NaN

### ISSUE THREAD

**Issue by sunshanjin** [youseries/uflo#9]
1、使用uflo流程引擎时，历史流程与任务中，历史任务结束日期出现NaN，uflo版本：2.0.2-SNAPSHOT；
截图：
![uflo_nan](https://user-images.githubusercontent.com/7366954/30906419-6585345e-a3aa-11e7-9655-fbf7d23f21fb.png)

**Comment by youseries** [comment]
更新最新的2.0.2-SNAPSHOT试试，谢谢。
